// src/data/staticData.js
const staticData = [
  {
    id: 1,
    name: "Item 1",
    category: "boxes",
    subCategory: "CLOTHIGS & APPARELS",
    heading: "Restyle Your Apparel and Clothing Packaging Boxes",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "Give Your Clothing Brand A Better Box to Wear",
    discription:
      "Elevate your apparel brading with custom boxes that suit your style. From custom box for shirt, t-shirt packaging boxes to trousers, dresses and whatnot, we help you craft all kinds of personalised clothing packaging.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Baby Clothes Folding Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Baby Clothes Hollow Rim Box with Slipcase White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Bed Sheets Slipcase Both Sides Open",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Cardboard Socks Sleeve",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Custom Clothing Box with Slip Lid White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Custom Clothing Box with Slipcase White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Custom Shirt Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading:
          "Custom Undergarment Folding Carton with Tuck in Flap Bottom/Top Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Lingerie Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "",
        heading: "Luxury Clothing Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "",
        heading: "Paper Box Undergarment Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "",
        heading: "Personalised Clothing Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 13,
        img: "",
        heading: "Sarees Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 14,
        img: "",
        heading: "Tie or Scarf Pillow Box",
        button: "",
        headerimg: "",

        subimg: "",
      },
      {
        Productid: 15,
        img: "",
        heading: "Undergarment Packaging Box",
        button: "",
        headerimg: "",

        subimg: "",
      },
    ],
    Review: "",
  },
  {
    id: 2,
    name: "Item 2",
    category: "boxes",
    subCategory: "CONSUMER GOODS",
    heading: "Refine Your Consumer Goods with a Better Box",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "From Goods to Goodies with Online Custom Packaging",
    discription:
      "Unbox your creativity and design boxes for packaging online with our innovative layouts. Build custom gift boxes with online tools by industries leading carton box manufacturers.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Board Game Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Bulb Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Butter Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Candle Drawer Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Cards Game Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Cookware Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Incense Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Jewellery Pillow Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "",
        heading: "Long Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Sleeve Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
];

export default staticData;
