// src/data/staticData.js
const staticData = [
  {
    id: 1,
    name: "Item 1",
    category: "boxes",
    subCategory: "CLOTHIGS & APPARELS",
    heading: "Restyle Your Apparel and Clothing Packaging Boxes",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "Give Your Clothing Brand A Better Box to Wear",
    discription:
      "Elevate your apparel brading with custom boxes that suit your style. From custom box for shirt, t-shirt packaging boxes to trousers, dresses and whatnot, we help you craft all kinds of personalised clothing packaging.",
    product: [
      {
        Productid: 1,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Baby Clothes Folding Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Baby Clothes Hollow Rim Box with Slipcase White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Bed Sheets Slipcase Both Sides Open",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cardboard Socks Sleeve",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Clothing Box with Slip Lid White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Clothing Box with Slipcase White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Shirt Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading:
          "Custom Undergarment Folding Carton with Tuck in Flap Bottom/Top Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Lingerie Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Luxury Clothing Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Paper Box Undergarment Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Personalised Clothing Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 13,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Sarees Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 14,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Tie or Scarf Pillow Box",
        button: "",
        headerimg: "",

        subimg: "",
      },
      {
        Productid: 15,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Undergarment Packaging Box",
        button: "",
        headerimg: "",

        subimg: "",
      },
    ],
    Review: "",
  },
  {
    id: 2,
    name: "Item 2",
    category: "boxes",
    subCategory: "CONSUMER GOODS",
    heading: "Refine Your Consumer Goods with a Better Box",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "From Goods to Goodies with Online Custom Packaging",
    discription:
      "Unbox your creativity and design boxes for packaging online with our innovative layouts. Build custom gift boxes with online tools by industries leading carton box manufacturers.",
    product: [
      {
        Productid: 1,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Board Game Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Bulb Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Butter Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Candle Drawer Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cards Game Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cookware Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Incense Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Jewellery Pillow Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Long Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Sleeve Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 3,
    name: "Item 3",
    category: "boxes",
    subCategory: "PERSONAL CARE & COSMETIC",
    heading: "Beautify Your Brand with Custom Cosmetic Box Designs",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "Dress your Cosmetics in a Desirable Custom Box",
    discription:
      "Redefine you cosmetic box design with the aid of our online packaging tools and layouts. Craft custom boxes for cosmetics in your desired materials and your brand colours. We even help you create gift boxes for cosmetics at lowest MOQ.",
    product: [
      {
        Productid: 1,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cosmetic Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cosmetic Gift Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Foundation Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Lipstick Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Skincare Kit Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Sanitary Pads Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Personal Care Kit Gift Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Makeup Box with Sleeve",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Slide / Drawer Cosmetic Packaging Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Soap Pillow Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Soap Sleeve Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 4,
    name: "Item 4",
    category: "boxes",
    subCategory: "BAKERY AND COOKIES",
    heading: "Custom Design Cake Boxes For a Flavourful Experience",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Explore Custom Bakery, Cookies and Biscuit Boxes Packaging",
    discription:
      "Show off your baked goods with custom cake boxes and bakery packaging. Use our online packaging design tool and explore enormous possibilities to make boxes for cupcakes, biscuit boxes, cookies boxes and other bakery goods. Turtle Boxes is the best cake box manufacturer in India. We deliver printed packaging PAN India, without the barrier of Minimum Order Quantity anytime, anywhere.",
    product: [
      {
        Productid: 1,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Biscuit Boxes Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cookie Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Cookies Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Cup Cake Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Oats Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Printed Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Printed Donut Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Food Tray Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Hexagonal Food Tray",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Macaron drawer Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Pre Mix Cake Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Rusk Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 5,
    name: "Item 5",
    category: "boxes",
    subCategory: "BEVERAGES",
    heading: "Box in the Goodness",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "Suave Packagings for Savoury Delights",
    discription:
      "Discover trending layouts and build a custom food and beverage packaging for those savoury delights. Craft your own custom box for packaging to boost your branding.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Beverage Paper Tray Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Card Box with Lid",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Custom Slipcase Boxes with Hallow Rim",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Custom Beverages Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Custom Slipcase Boxes ",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Juice Mono Carton Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Paper Folding Carton with Auto Locking",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Premium Wine Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Subscription Healthy Juice Packaging Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 6,
    name: "Item 6",
    category: "boxes",
    subCategory: "CHOCOLATES AND CONFECTIONERY",
    heading: "Unbox Your Packaging’s Potential",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Reimagine your Custom Chocolate Packaging Boxes with our Creative Templates",
    discription:
      "Craft a custom confectionary box to elevate your customer experience. Discover trending layouts of chocolate boxes for packaging. We help you craft boxes for your brand in premium chocolate packaging materials.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Chocolate Tray Hexagon Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Chocolate Bar Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Chocolate Box Sleeve",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Chocolate Combo Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Chocolate Packing Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Chocolate Slipcase Both Sides Open",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Chocolate Slipcase Tuck in Flap on One Side",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Fancy Chocolate Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Chocolate Tray Hexagon Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "",
        heading: "Fancy Chocolate Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "",
        heading: "Luxurious Chocolate Boxes with Lid",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "",
        heading: "Thin Chocolate Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 13,
        img: "",
        heading: "Paper Chocolate Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 14,
        img: "",
        heading: "Pillow Packaging for Chocolate",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 7,
    name: "Item 7",
    category: "boxes",
    subCategory: "FOOD & RESTAURANTS",
    heading: "Give Your Food Boxes Packaging an Appetizing Appeal",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Add a custom appeal to your appetizing meals with our online packaging tools.",
    discription:
      "Present your cuisine in a sensible and safe food box packaging. We help you craft custom food-grade packaging with our food packaging boxes design layouts. We are your food packaging manufacturers that help you design box food packaging online by yourself.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Biryani Slipcase Packing Both Sides",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Cereal Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Dry Fruits Paper Bags Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Food Boxes Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Food Container Sleeves Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Food Paper Tray Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Food Subscription Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Hexagon Paper Tray Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Ice Cream Packaging Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "",
        heading: "Kathi Roll Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "",
        heading: "Masala Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "",
        heading: "Oil Paper Carton Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 13,
        img: "",
        heading: "Sweets Packaging Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 8,
    name: "Item 8",
    category: "boxes",
    subCategory: "ECOMMERCE",
    heading: "Elevate with Custom E-Commerce Packaging & Boxes",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Take charge of all your packaging needs with our comprehensive packaging tools.",
    discription:
      "Uplift your customer interaction with ecommerce packaging that suits your brand. We provide you with your desired ecommerce packaging materials to elevate your brand’s appeal.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Custom Ecommerce Pillow Pouch",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Custom Folding Carton",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Custom Slipcase with Hollow Rim Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Ecommerce Hollow Rim Box with Slip Lid",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Ecommerce Slipcase Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Mailer Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Shipping Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 9,
    name: "Item 9",
    category: "boxes",
    subCategory: "COFFEE AND TEA",
    heading: "Brew a Custom Touch for Your Coffee & Tea Packaging",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Treat your brand to a custom tea box packaging with our online packaging tools.",
    discription:
      "Grace your tea packaging with elements of your brand by crafting a custom tea packaging box. Turtle Boxes is the ultimate carton box manufacturer to help you create your own coffee packaging with various tea packaging materials to choose from.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Coffee Gift Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Coffee Gift Hollow Rim Box with Slip Lid White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Green Tea Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Luxurious Hexagon Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Organic Coffee Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Premium Assorted Coffee Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Premium Coffee Gift Bag Packaging ",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Personalised Coffee Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Tea Paper Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "",
        heading: "Tea Coffee Subscription Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "",
        heading: "Premium Tea Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 10,
    name: "Item 10",
    category: "boxes",
    subCategory: "GIFTING",
    heading: "Add More Joy to Gifting with Custom Gift Boxes",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Grace your gifts with the personal touch of custom gift boxes.",
    discription:
      "A thoughtful gift is one that comes in a custom gift package box. Design online with our convenient tools and trending layouts of gift box for packaging. We help you craft custom gift boxes online in any dimension you require. Elevate your gifting with best custom boxes in India.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Custom Gift Box Bag",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Custom Gift Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Custom Printed Petals Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Gift Box for Packing",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Gift Package Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Gift Pillow Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Perfume Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Promotional Paper Gift Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 11,
    name: "Item 11",
    category: "boxes",
    subCategory: "FESTIVE COLLECTION",
    heading:
      "Festive Magic in Every Box! Explore Exclusive Ready-to-Use Festive Theme Printed Boxes",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Unbox the Festivals Spirit! Discover Festive Theme Printed Boxes",
    discription:
      "Our high-quality rigid cardboard boxes help you store, organize and protect your items. Whether you are looking for a way to transport clothing or collectables, these boxes are designed to suit your needs. They are reliable, easy to store and stackable, making them excellent for any occasion.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Ancient Artistry Brown Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Blooming Joy Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Festive Bouquet Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Festive Flair Orange Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Garden Grove Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Holiday Joy Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Spring Style Celebration Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Yellow Bahar Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Ethnic Era Magnetic Closure Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "",
        heading: "Purple Shine Drawer Style Rigid Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "",
        heading: "Ancient Artistry Green Top-Bottom (Telescopic) Rigid Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "",
        heading: "Blooming Joy Top-Bottom (Telescopic) Rigid Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 13,
        img: "",
        heading: "Holiday Joy Top-Bottom (Telescopic) Rigid Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 14,
        img: "",
        heading: "Holiday Joy Mailer Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 15,
        img: "",
        heading: "Turquoise Celebration Mailer Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 16,
        img: "",
        heading: "Ethnic Era Mailer Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 17,
        img: "",
        heading: "Festive Flair Orange Mailer Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 18,
        img: "",
        heading: "Ancient Artistry Green Self Locking Tray Hexagonal",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 19,
        img: "",
        heading: "Holiday Joy Self Locking Tray Hexagonal",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 20,
        img: "",
        heading: "Mauve Floral Pillow Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 21,
        img: "",
        heading: "Festive Treasure Pillow Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 22,
        img: "",
        heading: "Blooming Joy Pillow Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 23,
        img: "",
        heading: "Yellow Bahar Pillow Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 24,
        img: "",
        heading: "Blossom Breeze Pillow Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 12,
    name: "Item 12",
    category: "boxes",
    subCategory: "SAMPLE BOX SET",
    heading:
      "Order a sample set & grab a voucher worth Rs 500 for your next buy.",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "Sample Boxes Set as per Your Industry",
    discription:
      "Be your own quality control with your desired materials, print technique and finishes. Turtle Boxes offers Packaging Sample Set, as per your specific industry. Every Packaging Sample Set contains all material and finishing samples to give you a good overview of our packaging's stability and printing quality.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Cosmetic Sample Set",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Chocolate Sample Set",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Bakery Sample Set",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Cosmetic Sample Set",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Clothing Sample Set",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Food Sample Set",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Beverages Sample Set",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
];

export default staticData;
