// src/data/staticData.js
const staticData = [
  {
    id: 1,
    name: "Item 1",
    category: "boxes",
    subCategory: "CLOTHIGS & APPARELS",
    heading: "Restyle Your Apparel and Clothing Packaging Boxes",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "Give Your Clothing Brand A Better Box to Wear",
    discription:
      "Elevate your apparel brading with custom boxes that suit your style. From custom box for shirt, t-shirt packaging boxes to trousers, dresses and whatnot, we help you craft all kinds of personalised clothing packaging.",
    product: [
      {
        Productid: 1,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Baby Clothes Folding Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Baby Clothes Hollow Rim Box with Slipcase White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Bed Sheets Slipcase Both Sides Open",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cardboard Socks Sleeve",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Clothing Box with Slip Lid White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Clothing Box with Slipcase White Floor",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Shirt Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading:
          "Custom Undergarment Folding Carton with Tuck in Flap Bottom/Top Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Lingerie Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Luxury Clothing Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Paper Box Undergarment Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Personalised Clothing Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 13,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Sarees Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 14,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Tie or Scarf Pillow Box",
        button: "",
        headerimg: "",

        subimg: "",
      },
      {
        Productid: 15,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Undergarment Packaging Box",
        button: "",
        headerimg: "",

        subimg: "",
      },
    ],
    Review: "",
  },
  {
    id: 2,
    name: "Item 2",
    category: "boxes",
    subCategory: "CONSUMER GOODS",
    heading: "Refine Your Consumer Goods with a Better Box",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "From Goods to Goodies with Online Custom Packaging",
    discription:
      "Unbox your creativity and design boxes for packaging online with our innovative layouts. Build custom gift boxes with online tools by industries leading carton box manufacturers.",
    product: [
      {
        Productid: 1,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Board Game Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Bulb Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Butter Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Candle Drawer Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cards Game Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cookware Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Incense Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Jewellery Pillow Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Long Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Sleeve Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 3,
    name: "Item 3",
    category: "boxes",
    subCategory: "PERSONAL CARE & COSMETIC",
    heading: "Beautify Your Brand with Custom Cosmetic Box Designs",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "Dress your Cosmetics in a Desirable Custom Box",
    discription:
      "Redefine you cosmetic box design with the aid of our online packaging tools and layouts. Craft custom boxes for cosmetics in your desired materials and your brand colours. We even help you create gift boxes for cosmetics at lowest MOQ.",
    product: [
      {
        Productid: 1,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cosmetic Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cosmetic Gift Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Foundation Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Lipstick Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Skincare Kit Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Sanitary Pads Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Personal Care Kit Gift Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Makeup Box with Sleeve",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Slide / Drawer Cosmetic Packaging Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Soap Pillow Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Soap Sleeve Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 4,
    name: "Item 4",
    category: "boxes",
    subCategory: "BAKERY AND COOKIES",
    heading: "Custom Design Cake Boxes For a Flavourful Experience",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Explore Custom Bakery, Cookies and Biscuit Boxes Packaging",
    discription:
      "Show off your baked goods with custom cake boxes and bakery packaging. Use our online packaging design tool and explore enormous possibilities to make boxes for cupcakes, biscuit boxes, cookies boxes and other bakery goods. Turtle Boxes is the best cake box manufacturer in India. We deliver printed packaging PAN India, without the barrier of Minimum Order Quantity anytime, anywhere.",
    product: [
      {
        Productid: 1,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Biscuit Boxes Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Cookie Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Cookies Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Cup Cake Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Oats Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Printed Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Custom Printed Donut Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Food Tray Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Hexagonal Food Tray",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Macaron drawer Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Pre Mix Cake Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "https://turtleboxes.com/media/catalog/category/Chocolates_Confectionery.jpg",
        heading: "Rusk Packaging Box",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 5,
    name: "Item 5",
    category: "boxes",
    subCategory: "BEVERAGES",
    heading: "Box in the Goodness",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading: "Suave Packagings for Savoury Delights",
    discription:
      "Discover trending layouts and build a custom food and beverage packaging for those savoury delights. Craft your own custom box for packaging to boost your branding.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Beverage Paper Tray Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Card Box with Lid",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Custom Slipcase Boxes with Hallow Rim",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Custom Beverages Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Custom Slipcase Boxes ",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Juice Mono Carton Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Paper Folding Carton with Auto Locking",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Premium Wine Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Subscription Healthy Juice Packaging Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
  {
    id: 6,
    name: "Item 6",
    category: "boxes",
    subCategory: "CHOCOLATES AND CONFECTIONERY",
    heading: "Unbox Your Packaging’s Potential",
    mainImage: "src/assets/desktop-clothing-apparels.webp",
    discriptionHeading:
      "Reimagine your Custom Chocolate Packaging Boxes with our Creative Templates",
    discription:
      "Craft a custom confectionary box to elevate your customer experience. Discover trending layouts of chocolate boxes for packaging. We help you craft boxes for your brand in premium chocolate packaging materials.",
    product: [
      {
        Productid: 1,
        img: "",
        heading: "Chocolate Tray Hexagon Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 2,
        img: "",
        heading: "Chocolate Bar Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 3,
        img: "",
        heading: "Chocolate Box Sleeve",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 4,
        img: "",
        heading: "Chocolate Combo Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 5,
        img: "",
        heading: "Chocolate Packing Boxes",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 6,
        img: "",
        heading: "Chocolate Slipcase Both Sides Open",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 7,
        img: "",
        heading: "Chocolate Slipcase Tuck in Flap on One Side",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 8,
        img: "",
        heading: "Fancy Chocolate Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 9,
        img: "",
        heading: "Chocolate Tray Hexagon Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 10,
        img: "",
        heading: "Fancy Chocolate Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 11,
        img: "",
        heading: "Luxurious Chocolate Boxes with Lid",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 12,
        img: "",
        heading: "Thin Chocolate Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 13,
        img: "",
        heading: "Paper Chocolate Box Packaging",
        button: "",
        headerimg: "",
        subimg: "",
      },
      {
        Productid: 14,
        img: "",
        heading: "Pillow Packaging for Chocolate",
        button: "",
        headerimg: "",
        subimg: "",
      },
    ],
  },
];

export default staticData;
